"""HTML report generation with Tailwind CSS"""

from datetime import datetime
from pathlib import Path
from typing import Dict


class HTMLGenerator:
    """Generate HTML reports with Tailwind CSS"""
    
    def generate(self, metrics: Dict[str, str]) -> str:
        """Generate HTML report from metrics"""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kafka Performance Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        body {{ font-family: 'Inter', sans-serif; }}
    </style>
</head>
<body class="bg-gray-50 min-h-screen">
    <!-- Header -->
    <div class="bg-white border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-6 py-6">
            <div class="flex items-center justify-between">
                <div>
                    <h1 class="text-2xl font-bold text-gray-900">Kafka Performance Report</h1>
                    <p class="text-sm text-gray-500 mt-1">Generated on {timestamp}</p>
                </div>
                <div class="flex items-center gap-2 px-4 py-2 bg-gray-100 rounded-lg">
                    <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    <span class="text-sm font-medium text-gray-700">CLI Test</span>
                </div>
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-6 py-8">
        
        {self._generate_executive_summary(metrics)}
        {self._generate_test_config(metrics)}
        {self._generate_producer_metrics(metrics)}
        {self._generate_consumer_metrics(metrics)}

    </div>

    <!-- Footer -->
    <div class="bg-white border-t border-gray-200 mt-12">
        <div class="max-w-7xl mx-auto px-6 py-6">
            <div class="flex items-center justify-between text-sm text-gray-500">
                <p>Generated by <span class="font-medium text-gray-700">kafka-performance-test-wrapper</span></p>
                <p>{timestamp}</p>
            </div>
        </div>
    </div>

</body>
</html>
"""
        return html
    
    def _generate_executive_summary(self, m: Dict[str, str]) -> str:
        """Generate executive summary cards"""
        return f"""
        <!-- Executive Summary -->
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
                <div class="text-xs font-medium text-gray-500 uppercase mb-1">Target TPS</div>
                <div class="text-2xl font-bold text-gray-900">{m.get('target_tps', 'N/A')}</div>
                <div class="text-xs text-gray-500 mt-1">msg/s</div>
            </div>
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
                <div class="text-xs font-medium text-gray-500 uppercase mb-1">Payload Size</div>
                <div class="text-2xl font-bold text-gray-900">{m.get('payload_size', 'N/A')}</div>
                <div class="text-xs text-gray-500 mt-1">per message</div>
            </div>
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
                <div class="text-xs font-medium text-gray-500 uppercase mb-1">Duration</div>
                <div class="text-2xl font-bold text-gray-900">{m.get('duration', 'N/A')}</div>
                <div class="text-xs text-gray-500 mt-1">seconds</div>
            </div>
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
                <div class="text-xs font-medium text-gray-500 uppercase mb-1">Total Records</div>
                <div class="text-2xl font-bold text-gray-900">{m.get('num_records', 'N/A')}</div>
                <div class="text-xs text-gray-500 mt-1">messages</div>
            </div>
        </div>
        """
    
    def _generate_test_config(self, m: Dict[str, str]) -> str:
        """Generate test configuration section"""
        return f"""
        <!-- Test Configuration -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 mb-6">
            <div class="px-6 py-4 border-b border-gray-200">
                <h2 class="text-lg font-semibold text-gray-900">Test Configuration</h2>
            </div>
            <div class="px-6 py-4">
                <dl class="grid grid-cols-1 gap-4">
                    <div class="flex justify-between py-3 border-b border-gray-100">
                        <dt class="text-sm font-medium text-gray-600">Topic</dt>
                        <dd class="text-sm text-gray-900 font-mono">{m.get('topic', 'N/A')}</dd>
                    </div>
                    <div class="flex justify-between py-3 border-b border-gray-100">
                        <dt class="text-sm font-medium text-gray-600">Bootstrap Servers</dt>
                        <dd class="text-sm text-gray-900 font-mono">{m.get('bootstrap', 'N/A')}</dd>
                    </div>
                    <div class="flex justify-between py-3">
                        <dt class="text-sm font-medium text-gray-600">Producer Configuration</dt>
                        <dd class="text-sm text-gray-900 font-mono">{m.get('producer_config', 'N/A')}</dd>
                    </div>
                </dl>
            </div>
        </div>
        """
    
    def _generate_producer_metrics(self, m: Dict[str, str]) -> str:
        """Generate producer performance section"""
        return f"""
        <!-- Producer Metrics -->
        <div class="bg-white rounded-lg shadow-sm border-l-4 border-l-blue-500 border-r border-t border-b border-gray-200 mb-6">
            <div class="px-6 py-4 border-b border-gray-200 bg-gradient-to-r from-blue-50 to-white">
                <div class="flex items-center gap-3">
                    <div class="bg-blue-500 rounded-lg p-2">
                        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path>
                        </svg>
                    </div>
                    <h2 class="text-lg font-semibold text-gray-900">Producer Performance</h2>
                    <span class="ml-auto text-xs font-medium text-blue-700 bg-blue-100 px-2 py-1 rounded">WRITE</span>
                </div>
            </div>
            
            <!-- Key Metrics Grid -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-6">
                <!-- TPS -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Throughput (TPS)</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('tps', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">msg/s · target {m.get('target_tps', 'N/A')}</div>
                </div>

                <!-- Throughput -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Data Rate</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('mbps', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">throughput</div>
                </div>

                <!-- Avg Latency -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Avg Latency</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('avg_ms', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">milliseconds</div>
                </div>

                <!-- Max Latency -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Max Latency</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('max_ms', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">milliseconds</div>
                </div>
            </div>

            <!-- Latency Percentiles -->
            <div class="px-6 pb-6">
                <h3 class="text-sm font-semibold text-gray-900 mb-4">Latency Distribution</h3>
                <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
                    <!-- P50 -->
                    <div class="bg-gray-50 rounded-lg p-3 border border-gray-200">
                        <div class="text-xs font-medium text-gray-500 uppercase mb-1">P50 (Median)</div>
                        <div class="text-xl font-bold text-gray-900">{m.get('p50', 'N/A')}</div>
                        <div class="text-xs text-gray-600">ms</div>
                    </div>
                    <!-- P95 -->
                    <div class="bg-gray-50 rounded-lg p-3 border border-gray-200">
                        <div class="text-xs font-medium text-gray-500 uppercase mb-1">P95</div>
                        <div class="text-xl font-bold text-gray-900">{m.get('p95', 'N/A')}</div>
                        <div class="text-xs text-gray-600">ms</div>
                    </div>
                    <!-- P99 -->
                    <div class="bg-gray-50 rounded-lg p-3 border border-gray-200">
                        <div class="text-xs font-medium text-gray-500 uppercase mb-1">P99</div>
                        <div class="text-xl font-bold text-gray-900">{m.get('p99', 'N/A')}</div>
                        <div class="text-xs text-gray-600">ms</div>
                    </div>
                    <!-- P99.9 -->
                    <div class="bg-gray-50 rounded-lg p-3 border border-gray-200">
                        <div class="text-xs font-medium text-gray-500 uppercase mb-1">P99.9</div>
                        <div class="text-xl font-bold text-gray-900">{m.get('p999', 'N/A')}</div>
                        <div class="text-xs text-gray-600">ms</div>
                    </div>
                </div>
                <div class="mt-4 pt-4 border-t border-gray-200">
                    <div class="flex justify-between text-sm">
                        <span class="font-medium text-gray-700">Total Records Sent</span>
                        <span class="font-mono text-gray-900">{m.get('records', 'N/A')}</span>
                    </div>
                </div>
            </div>
        </div>
        """
    
    def _generate_consumer_metrics(self, m: Dict[str, str]) -> str:
        """Generate consumer performance section"""
        return f"""
        <!-- Consumer Metrics -->
        <div class="bg-white rounded-lg shadow-sm border-l-4 border-l-purple-500 border-r border-t border-b border-gray-200 mb-6">
            <div class="px-6 py-4 border-b border-gray-200 bg-gradient-to-r from-purple-50 to-white">
                <div class="flex items-center gap-3">
                    <div class="bg-purple-500 rounded-lg p-2">
                        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10"></path>
                        </svg>
                    </div>
                    <h2 class="text-lg font-semibold text-gray-900">Consumer Performance</h2>
                    <span class="ml-auto text-xs font-medium text-purple-700 bg-purple-100 px-2 py-1 rounded">READ</span>
                </div>
            </div>
            
            <!-- Key Metrics Grid -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-6">
                <!-- TPS -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Throughput (TPS)</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('consumer_msgps', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">msg/s read</div>
                </div>

                <!-- Data Rate -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Data Rate</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('consumer_mbps', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">MB/s throughput</div>
                </div>

                <!-- Messages Consumed -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Messages</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('consumer_msgs', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">total read</div>
                </div>

                <!-- Data Consumed -->
                <div class="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
                    <div class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Data Volume</div>
                    <div class="text-3xl font-bold text-gray-900">{m.get('consumer_mb', 'N/A')}</div>
                    <div class="text-xs text-gray-600 mt-1">total read</div>
                </div>
            </div>

            <!-- Time & Performance Details -->
            <div class="px-6 pb-6">
                <!-- Time Window -->
                <div class="bg-gradient-to-br from-gray-50 to-gray-100 rounded-lg p-4 border border-gray-200 mb-4">
                    <div class="flex items-center justify-between">
                        <div class="flex-1">
                            <div class="text-xs font-medium text-gray-500 uppercase mb-2">Time Window</div>
                            <div class="text-sm font-mono text-gray-900 mb-1">{m.get('consumer_start', 'N/A')} → {m.get('consumer_end', 'N/A')}</div>
                            <div class="flex items-center gap-2 mt-2">
                                <span class="text-xs font-medium text-gray-600">Duration:</span>
                                <span class="text-lg font-bold text-gray-900">{m.get('consumer_duration', 'N/A')}s</span>
                            </div>
                        </div>
                        <svg class="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                    </div>
                </div>
                
                <!-- Fetch Performance -->
                <div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
                    <div class="flex items-center gap-2 mb-3">
                        <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                        <h3 class="text-sm font-semibold text-gray-900">Fetch Performance Metrics</h3>
                    </div>
                    <p class="text-xs text-gray-600 mb-4">Performance metrics for fetch operations (reading from Kafka broker)</p>
                    
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div class="bg-white rounded-lg p-4 border border-gray-200">
                            <div class="text-xs font-medium text-gray-500 uppercase mb-1">Fetch Time</div>
                            <div class="text-2xl font-bold text-gray-900">{m.get('consumer_fetch_ms', 'N/A')} ms</div>
                            <div class="text-xs text-gray-600 mt-2">Total time spent fetching data from broker</div>
                        </div>
                        <div class="bg-white rounded-lg p-4 border border-gray-200">
                            <div class="text-xs font-medium text-gray-500 uppercase mb-1">Fetch Data Rate</div>
                            <div class="text-2xl font-bold text-gray-900">{m.get('consumer_fetch_mbps', 'N/A')} MB/s</div>
                            <div class="text-xs text-gray-600 mt-2">Data transfer rate during fetch operations</div>
                        </div>
                        <div class="bg-white rounded-lg p-4 border border-gray-200">
                            <div class="text-xs font-medium text-gray-500 uppercase mb-1">Fetch Message Rate</div>
                            <div class="text-2xl font-bold text-gray-900">{m.get('consumer_fetch_msgps', 'N/A')} msg/s</div>
                            <div class="text-xs text-gray-600 mt-2">Message rate during fetch operations</div>
                        </div>
                    </div>
                </div>
                
                <!-- Rebalance Time -->
                <div class="mt-4 bg-blue-50 rounded-lg p-3 border border-blue-200">
                    <div class="flex items-center justify-between">
                        <span class="text-sm font-medium text-blue-900">Rebalance Time</span>
                        <span class="text-lg font-bold text-blue-900">{m.get('consumer_rebalance_ms', 'N/A')} ms</span>
                    </div>
                </div>
            </div>
        </div>
        """
    
    def save(self, html: str, output_path: Path):
        """Save HTML report to file"""
        output_path.write_text(html)
